name: DockPeek
options:
  bundleIdPrefix: com.dockpeek
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "5.9"

targets:
  DockPeek:
    type: application
    platform: macOS
    sources:
      - path: DockPeek
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dockpeek.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: DockPeek/Info.plist
        CODE_SIGN_ENTITLEMENTS: DockPeek/DockPeek.entitlements
        COMBINE_HIDPI_IMAGES: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
